# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
    ]
