# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mik', '0002_auto_20170709_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(verbose_name='Дата публикиции'),
        ),
    ]
